image: trion/ng-cli-karma

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/
    - dist/

before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass tree
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa

Build:
  stage: build
  only:
    - merge_requests
  script:
    - rm ./package-lock.json
    - npm install
    - ng build --progress false --prod
    - tree dist/

Test:
  stage: test
  only:
    - merge_requests
  script:
    - ng test StarbreakersNet-Website --watch=false

Deploy_Beta:
  stage: deploy
  environment:
    name: Beta
  only:
    - develop
  script:
    - ng build --progress false --prod
    - ssh -i ~/.ssh/id_rsa -o stricthostkeychecking=no gitlab-agent@starbreakersgaming.com 'rm -rf /srv/www/starbreakersnet-website-beta/*'
    - scp -i ~/.ssh/id_rsa -o stricthostkeychecking=no -r ./*/* gitlab-agent@starbreakersgaming.com:/srv/www/starbreakersnet-website-beta/

Deploy_Production:
  stage: deploy
  environment:
    name: Production
  only:
    - master
    - tags
  script:
    - ng build --progress false --prod
    - ssh -i ~/.ssh/id_rsa -o stricthostkeychecking=no gitlab-agent@starbreakersgaming.com 'rm -rf /srv/www/starbreakersnet-website/*'
    - scp -i ~/.ssh/id_rsa -o stricthostkeychecking=no -r ./*/* gitlab-agent@starbreakersgaming.com:/srv/www/starbreakersnet-website/
