image: trion/ng-cli-karma

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/
    - dist/

before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass tree
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa

Build:
  stage: build
  only:
    - merge_requests
  script:
    - rm ./package-lock.json
    - npm install
    - ng build --progress false --prod
    - tree dist/

Test:
  stage: test
  only:
    - merge_requests
  script:
    - ng test starbreakersnet-website --watch=false

Deploy_Beta:
  stage: deploy
  environment:
    name: Beta
  only:
    - /.*-beta$/
  except:
    - branches
  script:
    - ng build --progress false --prod
    - ssh -i ~/.ssh/id_rsa -o stricthostkeychecking=no starbreakers-agent@starbreakersgaming.com 'rm -rf $DEPLOY_BETA_PATH/*'
    - scp -i ~/.ssh/id_rsa -o stricthostkeychecking=no -r dist/*/* starbreakers-agent@starbreakersgaming.com:$DEPLOY_BETA_PATH/

Deploy_Production:
  stage: deploy
  environment:
    name: Production
  only:
    - /.*\d$/
  except:
    - branches
  script:
    - rm ./package-lock.json
    - npm install
    - ./node_modules/@angular/cli/bin/ng build --progress false --prod
    - cd dist/
    - ssh -i ~/.ssh/id_rsa -o stricthostkeychecking=no starbreakers-agent@starbreakersgaming.com 'rm -rf $DEPLOY_PROD_PATH/*'
    - scp -i ~/.ssh/id_rsa -o stricthostkeychecking=no -r ./*/* starbreakers-agent@starbreakersgaming.com:$DEPLOY_PROD_PATH/
