image: node:18.20.4

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - dist/

before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass tree
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa

Build:
  stage: build
  only:
    - merge_requests
  script:
    - npm install
    - npm run build
    - tree dist/

Deploy_Beta:
  stage: deploy
  environment:
    name: Beta
  only:
    - /.*-beta$/
  except:
    - branches
  script:
    - npm run build
    - ssh -i ~/.ssh/id_rsa -o stricthostkeychecking=no starbreakers-agent@starbreakers.net 'rm -rf /beta.starbreakers.net/*'
    - scp -i ~/.ssh/id_rsa -o stricthostkeychecking=no -r dist/* starbreakers-agent@starbreakers.net:/beta.starbreakers.net/

Deploy_Production:
  stage: deploy
  environment:
    name: Production
  only:
    - /.*\d$/
  except:
    - branches
  script:
    - npm run build
    - ssh -i ~/.ssh/id_rsa -o stricthostkeychecking=no starbreakers-agent@starbreakers.net 'rm -rf /httpdocs/*'
    - scp -i ~/.ssh/id_rsa -o stricthostkeychecking=no -r dist/* starbreakers-agent@starbreakers.net:/httpdocs/
